import type { NextPage } from 'next'
import Head from 'next/head'
import { Layout } from '../components/layout'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Sales App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout />
    </div>
  )
}

export default Home
